{{- if .Values.networks }}
{{- range .Values.networks }}
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .name }}
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": {"ips": true},
          "master": {{ .master | quote }},
          "mode": "bridge",
          "ipam": {"type": "static"}
        },
        {"type": "tuning"}
      ]
    }
...
{{- end -}}
{{- end -}}