apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "xrd.fullname" . }}-config
{{- if .Values.config }}
{{- if or .Values.config.ascii .Values.config.script }}
data:
  {{- if .Values.config.ascii }}
  startup.cfg: |
    {{- .Values.config.ascii | default "" | nindent 4 }}
  {{- end }}
  {{- if .Values.config.script }}
  startup.sh: |
    {{- .Values.config.script | nindent 4 }}
  {{- end }}
{{- else }}
data: {}
{{- end -}}
{{- else }}
data: {}
{{- end -}}
